CC=gcc
CFLAGS=-Wall -std=c11 -pedantic -g
FILES= bottom_up.c Parser.c scanner.c symtable.c ASS.c ifj.c c206.c symdll.c test.c


all: compile 

cleanpile: compile

compile:
	$(CC) $(CFLAGS) $(FILES) -o ifj 


